// examples/react/fields-basic/src/App.tsx
import { useState, useMemo } from 'react';
import { useSpotr } from 'spotr/react';
import peopleJson from './data/people.json';
import type { Person } from './types';
import { getNestedValue, highlightCellValue } from './utils';

const peopleData: Person[] = peopleJson as Person[];

const title = 'Fields - Basic';
const columns = ['firstName', 'lastName', 'email'];
const examples = ['alice', 'aloce', 'wayne', 'acme.com'];
const LIMIT = 20;

function App() {
  const [query, setQuery] = useState('');
  const spotr = useSpotr({
    collection: peopleData,
    threshold: 0.3,
    fields: [
      { name: 'firstName', weight: 1 },
      { name: 'lastName', weight: 1 },
      { name: 'email', weight: 0.8 },
    ],
    limit: LIMIT,
  });

  const result = useMemo(() => {
    if (!query.trim()) {
      return {
        results: peopleData
          .slice(0, LIMIT)
          .map((item) => ({ item, score: null as number | null })),
        matchedKeywords: [] as { name: string; terms: string[] }[],
        tokens: [] as string[],
        warnings: [] as string[],
      };
    }
    return spotr.query(query);
  }, [spotr, query]);

  return (
    <div className="container">
      <h1 className="title">{title}</h1>
      <input
        type="search"
        value={query}
        onChange={(e) => setQuery(e.target.value)}
        placeholder="Search..."
        className="input"
      />
      <div className="buttons">
        {examples.map((ex) => (
          <button key={ex} onClick={() => setQuery(ex)} className="button">
            {ex}
          </button>
        ))}
      </div>
      <table className="table">
        <thead>
          <tr>
            <th className="th">Score</th>
            {columns.map((col) => (
              <th key={col} className="th">
                {col}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {result.results.map((r, i) => (
            <tr key={i} className="tr">
              <td className="td">
                {r.score != null ? r.score.toFixed(2) : '-'}
              </td>
              {columns.map((col) => (
                <td key={col} className="td">
                  <span
                    dangerouslySetInnerHTML={{
                      __html: highlightCellValue(
                        getNestedValue(r.item, col),
                        col,
                        result.matchedKeywords
                      ),
                    }}
                  />
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default App;

// examples/vue/fields-basic/src/App.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { useSpotr } from 'spotr/vue';
import peopleJson from './data/people.json';
import type { Person } from './types';
import { getNestedValue, highlightCellValue } from './utils';

const peopleData: Person[] = peopleJson as Person[];

const title = 'Fields - Basic';
const columns = ['firstName', 'lastName', 'email'];
const examples = ['alice', 'aloce', 'wayne', 'acme.com'];
const LIMIT = 20;

const query = ref('');
const spotrRef = useSpotr({
  collection: peopleData,
  threshold: 0.3,
  fields: [
    { name: 'firstName', weight: 1 },
    { name: 'lastName', weight: 1 },
    { name: 'email', weight: 0.8 },
  ],
  limit: LIMIT,
});

const result = computed(() => {
  if (!query.value.trim()) {
    return {
      results: peopleData
        .slice(0, LIMIT)
        .map((item) => ({ item, score: null as number | null })),
      matchedKeywords: [] as { name: string; terms: string[] }[],
      tokens: [] as string[],
      warnings: [] as string[],
    };
  }
  return (
    spotrRef.value?.query(query.value) ?? {
      results: [],
      matchedKeywords: [],
      tokens: [],
      warnings: [],
    }
  );
});
</script>

<template>
  <div class="container">
    <h1 class="title">{{ title }}</h1>
    <input
      v-model="query"
      type="search"
      placeholder="Search..."
      class="input"
    />
    <div class="buttons">
      <button
        v-for="ex in examples"
        :key="ex"
        class="button"
        @click="query = ex"
      >
        {{ ex }}
      </button>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th class="th">Score</th>
          <th v-for="col in columns" :key="col" class="th">{{ col }}</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(r, i) in result.results" :key="i" class="tr">
          <td class="td">{{ r.score != null ? r.score.toFixed(2) : '-' }}</td>
          <td
            v-for="col in columns"
            :key="col"
            class="td"
            v-html="
              highlightCellValue(
                getNestedValue(r.item, col),
                col,
                result.matchedKeywords
              )
            "
          />
        </tr>
      </tbody>
    </table>
  </div>
</template>
